name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1  Grab the code
      - uses: actions/checkout@v4

      # 2  Set up Python (adjust if you prefer another version)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3  Install deps (Poetry or pip—pick one)
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt  # swap for `poetry install` if you use Poetry

      # 4  Run a placeholder test
      - name: Run tests
        run: |
          echo "No tests yet — CI green ✅"
